### PR TITLE
Minor fixes #89 fixes #90

### LINKED ISSUE #89: make extension lowercase in application_submission script it is not matching the extension array if extension is in uppercase
Fix for multiple file uploads

### LINKED ISSUE #90: show "no uploads" in table when no files are uploaded

### PR DESCRIPTION
**Pull request by thesmallstar**
proff1
proff2

issue: #89 
issue: #90

### CODE REVIEW

**Comment by thesmallstar** [comment]
@prateek76  I have updated my repo to upstream master but I see one of the file I did not change, any reason for that?

**Comment by prateek76** [comment]
@thesmallstar check your folder if you have extra signupcheck.php file in root directory , one will be in core folder

**Comment by thesmallstar** [comment]
Okay. :)

**Comment by thesmallstar** [comment]
@prateek76 I think the problem is fixed now.

**Pull request merged**
