### PR TITLE
fixes #41 Reduced space between buttons.

### LINKED ISSUE #41: reduce space b/w buttons in sidenav
Reduce space and also remove underline on hovering new application button in students_dashboard

### PR DESCRIPTION
**Pull request by thesmallstar**
Button underline was fixed earlier. 
fix for buttons

### CODE REVIEW

**Comment by prateek76** [comment]
@thesmallstar  same for admin dashboard

**Comment by thesmallstar** [comment]
button fix
Done :)

**Comment by prateek76** [comment]
have you pushed @thesmallstar

**Comment by thesmallstar** [comment]
@prateek76 I did, Something might have been wrong. I have pushed the same changes again. :)

**Pull request merged**
