### PR TITLE
add a loader (spinner) while table contents loads everytime #97

### PR DESCRIPTION
**Pull request by vishnuk7**
issue #97 solved

### CODE REVIEW

**Comment by prateek76** [comment]
@vishnuk7 resolve the conflicts

**Comment by vishnuk7** [comment]
@prateek76  conflicts resolved

**Comment by prateek76** [comment]
@vishnuk7 again changes in each line in the student dashboard file

**Comment by vishnuk7** [comment]
I don't know how this is happening again and again 😭
@prateek76 check this out #112

**Pull request closed without merging**
