### PR TITLE
Issue54

### PR DESCRIPTION
**Pull request by vishnuk7**
Implement add more files option in students dashboard modal 
issue #54 solved

**before adding files**

image

***

image

***

**after adding two files**
image

### CODE REVIEW

**Comment by prateek76** [comment]
@vishnuk7 also @thesmallstar commits are also present in your pr drop that commit

**Comment by vishnuk7** [comment]
> @vishnuk7 student dashboard file is showing changes in each line fix that

@prateek76 
I don't know how to fix this,
Can I close this issue and make a new pr

**Comment by prateek76** [comment]
you can any number of pr for an issue @vishnuk7

**Comment by prateek76** [comment]
also, you can pick and drop commits in git-rebase while squashing, there you can drop the commit you don't want

**Pull request closed without merging**
