### PR TITLE
scrolling removed

### PR DESCRIPTION
**Pull request by Rattlecode17sh**
Issue #13

### CODE REVIEW

**Comment by prateek76** [comment]
@Rattlecode17sh attach screenshots for different devices (iphoneX and desktop view will do in 100% size)

**Comment by Rattlecode17sh** [comment]
screenshot 39
screenshot 40
screenshot 41
screenshot 42

**Comment by Rattlecode17sh** [comment]
Have a look and let me know about other changes requierd

**Comment by prateek76** [comment]
> Have a look and let me know about other changes requierd

remove analytics button as well

**Pull request merged**
