### PR TITLE
Trimmed values and checked for empty password.

### PR DESCRIPTION
**Pull request by thesmallstar**
1. I am storing the trimmed value and checking if that is empty. Since trimming the original value is not a solution considering that name and password can contain the spaces. The only condition is that they should not be only white spaces. Can you quickly guide how should  I squash merges. Debck guided me before but I am facing some issues again. 

new_2

new_1

### CODE REVIEW

**Comment by prateek76** [comment]
@thesmallstar 
https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by prateek76** [comment]
@thesmallstar use pick in first commit and s in front of your other commits

**Comment by thesmallstar** [comment]
@prateek76  nothing seems to be working rebase command messes things up.

**Comment by prateek76** [comment]
@thesmallstar can you tell what is the problem you are facing ?

**Comment by thesmallstar** [comment]
@prateek76  I messed a few things with this repo, and hence I am facing problems. I will take care of things from the next time :) For now please review the new PR.

**Pull request closed without merging**
