### PR TITLE
Removed all errors and no-file file form submission  fixes #53

### LINKED ISSUE #53: Error on submitting new application
when submitting new application without uploading image it's showing alert box errors remove that, also remove all alert boxes involved

### PR DESCRIPTION
**Pull request by thesmallstar**
issue: #53

### CODE REVIEW

**Comment by thesmallstar** [comment]
I am not sure why I get the file changed from the last PRs any idea about that?
suc1
er1

**Comment by prateek76** [comment]
@thesmallstar did you made pr from this branch for last issue?

**Comment by thesmallstar** [comment]
Yes, also,it was merged.

**Comment by prateek76** [comment]
@thesmallstar try making pr with new branch

**Comment by thesmallstar** [comment]
You mean I should scrap this PR? From next time I will also create new branches for every issue.

**Comment by prateek76** [comment]
@thesmallstar delete the branch after your pr is merged alway try to make pr from a new branch

**Comment by thesmallstar** [comment]
Okay, I will remember that :)

**Comment by thesmallstar** [comment]
@prateek76  this PR still solves the issue mentioned do I need to change anything in this one ?

**Comment by prateek76** [comment]
> @prateek76 this PR still solves the issue mentioned do I need to change anything in this one ?

it contain previous commits, can you make a new pr for this?

**Comment by thesmallstar** [comment]
@prateek76  I have only one branch, Um I guess the changes are already merged. So it won't affect, also the files dont appear in files changed so it is actually adding only new changes.

**Comment by thesmallstar** [comment]
@prateek76  I have tried my best, new weird issues keep coming. I have decided to delete the forked repo and fork it again and then make all the changes. Do you have any suggestion?

**Comment by prateek76** [comment]
> @prateek76 I have tried my best, new weird issues keep coming. I have decided to delete the forked repo and fork it again and then make all the changes. Do you have any suggestion?

is your master up to date?

**Comment by thesmallstar** [comment]
I messed up with master while squashing commits. I tried creating new branch and then pull upstream but it is showing 1 file changed( I didnt find a reason for this)
https://github.com/GeekHaven/Leave-Application-Portal/compare/master...thesmallstar:master
And hence, I am not able to make a branch which is even with your master.

**Comment by prateek76** [comment]
> I messed up with master while squashing commits. I tried creating new branch and then pull upstream but it is showing 1 file changed( I didnt find a reason for this)
> [master...thesmallstar:master](https://github.com/GeekHaven/Leave-Application-Portal/compare/master...thesmallstar:master)
> And hence, I am not able to make a branch which is even with your master.
have you tried cloning again?

**Comment by thesmallstar** [comment]
@prateek76  Yes I did try cloning again. Gives me the same Error.
what else can be wrong? I am stuck here.

**Comment by thesmallstar** [comment]
@prateek76 the file changed it is showing are the one already merged. I don't know what can be causing it. Should I just recreate the repo? This pr keeps me stuck.

**Comment by thesmallstar** [comment]
Sir, That was a lifesaver :D

**Comment by thesmallstar** [comment]
@prateek76  It worked :D Everything LG now.

**Pull request merged**
